# Generated by Django 6.0.1 on 2026-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
