# Generated by Django 6.0.1 on 2026-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reminder_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reminder_time",
            field=models.TimeField(default="09:00"),
        ),
    ]
