# Generated by Django 6.0.1 on 2026-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_reminder_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_on_leaderboard",
            field=models.BooleanField(default=True),
        ),
    ]
