services:
  - type: web
    name: smart-assessment-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13