# Generated by Django 6.0.1 on 2026-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quizsession_quizresult_question_useranswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
